travis:
  secure:
    BINSTAR_TOKEN: hJYOsEZStyAvnM6ITVl89L8K6ayOzxDciNCBW3C2QMICBdWMsDuDE/OX8ljQsJ+bOXoQnsAFKBQKuixoSc8mtxv2eF33aZqDILt9LgGoVCAN1ocYFNxB/3ZafvcShvaKISA/z7NWlt+n/0XhAdIv6zQ99r1vlDhodkBqdvqgAEBqWdjE+J1YtiX7YwgTWbF9tkjMKBXW+slM5lTRu7OcrAE3WwcVyDMysD0kyWEOEiuVYHXJRM0zfdbVffLt1/0xFwHBRlFUVeHufVitpSgF+MgLm2//WP1bcmR/buOZi9m1pOiAOzV2lGmpre6G4++FyutKVsuh4RqsNQ5cPvPoPCc8xSqS1xahF9fwZWHTIf5l8OjPZgnchS3Hcr7hBWZ8LsGuIk0KnjTKvIN7U17KyZlmZCJFuHkOoP700iNX0+ttIrmOb1SlhYtOmaeThlj0S9M+9pwI00W1qsNzrMmQIf5hXdVBR9tzhWmjPZw2GnIRlHSO8lA6ER2JVuAW4JNI9vXN1byFO9ohFY6T4/3Yh0Jc8GkqE9OIZIp/gCa/Glp5aU0Z38PmMmu1WNZ+JKJylBwUPqhxABLVTUHG00lrDLI6kzN0Pn+7jpVIXsrpmlqtY8aDSFEJPdCyTNI6qkMewyNeaZ5CGOWnKeiR9wun9d6sWaTfZhySf2KogmBmx2E=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
